# Generated by Django 5.2.6 on 2025-09-20 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=20, unique=True, verbose_name='Numéro de compte')),
                ('type_compte', models.CharField(choices=[('admin', 'Administrateur'), ('gerant', 'Gérant'), ('caissier', 'Caissier'), ('vendeur', 'Vendeur'), ('magasinier', 'Magasinier'), ('comptable', 'Comptable')], default='vendeur', max_length=20, verbose_name='Type de compte')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.agence', verbose_name='Agence')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur Django')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_employe', models.CharField(max_length=20, unique=True, verbose_name='Numéro employé')),
                ('poste', models.CharField(max_length=100, verbose_name='Poste')),
                ('departement', models.CharField(choices=[('vente', 'Vente'), ('caisse', 'Caisse'), ('stock', 'Stock'), ('comptabilite', 'Comptabilité'), ('administration', 'Administration'), ('direction', 'Direction')], max_length=50, verbose_name='Département')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire de base')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('licencie', 'Licencié')], default='actif', max_length=20, verbose_name='Statut')),
                ('contact_urgence_nom', models.CharField(max_length=100, verbose_name="Nom du contact d'urgence")),
                ('contact_urgence_telephone', models.CharField(max_length=20, verbose_name="Téléphone du contact d'urgence")),
                ('contact_urgence_relation', models.CharField(max_length=50, verbose_name="Relation avec le contact d'urgence")),
                ('adresse_personnelle', models.TextField(verbose_name='Adresse personnelle')),
                ('ville_personnelle', models.CharField(max_length=100, verbose_name='Ville personnelle')),
                ('code_postal_personnel', models.CharField(max_length=10, verbose_name='Code postal personnel')),
                ('numero_secu', models.CharField(max_length=15, unique=True, verbose_name='Numéro de sécurité sociale')),
                ('numero_cnss', models.CharField(max_length=20, verbose_name='Numéro CNSS')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('peut_gerer_caisse', models.BooleanField(default=False, verbose_name='Peut gérer la caisse')),
                ('peut_gerer_stock', models.BooleanField(default=False, verbose_name='Peut gérer le stock')),
                ('peut_voir_statistiques', models.BooleanField(default=False, verbose_name='Peut voir les statistiques')),
                ('peut_gerer_comptabilite', models.BooleanField(default=False, verbose_name='Peut gérer la comptabilité')),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supermarket.compte', verbose_name='Compte')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['compte__nom', 'compte__prenom'],
            },
        ),
        migrations.AddField(
            model_name='factureachat',
            name='responsable_achat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.employe', verbose_name='Responsable achat'),
        ),
        migrations.AddField(
            model_name='facturetransfert',
            name='responsable_transfert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.employe', verbose_name='Responsable transfert'),
        ),
        migrations.AddField(
            model_name='facturevente',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.employe', verbose_name='Vendeur'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='responsable_inventaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.employe', verbose_name='Responsable inventaire'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='responsable_mouvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.employe', verbose_name='Responsable mouvement'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarket.employe', verbose_name='Employé'),
        ),
    ]
