# Generated by Django 5.2.6 on 2025-09-23 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0003_remove_facturetransfert_code_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignefacturevente',
            name='type_vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarket.typevente', verbose_name='Type de vente'),
        ),
    ]
