# Generated by Django 5.2.6 on 2024-07-29 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supermarket', '0006_facturevente_session_caisse'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_document', models.CharField(max_length=50, unique=True, verbose_name='Numéro du document')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_fermeture', models.DateTimeField(verbose_name='Heure de fermeture')),
                ('vendeuse_nom', models.CharField(max_length=200, verbose_name='Nom de la vendeuse')),
                ('nombre_factures', models.IntegerField(default=0, verbose_name='Nombre de factures')),
                ('total_articles', models.IntegerField(default=0, verbose_name='Total articles vendus')),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Chiffre d'affaires")),
                ('factures_data', models.JSONField(verbose_name='Données des factures')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.agence', verbose_name='Agence')),
                ('session_caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.sessioncaisse', verbose_name='Session de caisse')),
            ],
            options={
                'verbose_name': 'Document de vente',
                'verbose_name_plural': 'Documents de vente',
                'ordering': ['-date', '-heure_fermeture'],
            },
        ),
    ]








