# Generated by Django 5.2.6 on 2025-09-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0007_documentvente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureTemporaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Clé de session')),
                ('contenu', models.JSONField(verbose_name='Contenu de la facture')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Facture Temporaire',
                'verbose_name_plural': 'Factures Temporaires',
                'ordering': ['-date_modification'],
            },
        ),
    ]
