# Generated by Django 5.2.6 on 2025-09-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0008_facturetemporaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignefacturevente',
            name='type_vente',
        ),
        migrations.AlterField(
            model_name='facturevente',
            name='session_caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarket.sessioncaisse', verbose_name='Session de caisse'),
        ),
    ]
