# Generated by Django 5.2.6 on 2025-09-24 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0009_add_session_caisse_and_document_vente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturetemporaire',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Facture temporaire', 'verbose_name_plural': 'Factures temporaires'},
        ),
        migrations.AlterField(
            model_name='facturetemporaire',
            name='session_key',
            field=models.CharField(max_length=100, verbose_name='Clé de session'),
        ),
        migrations.AlterField(
            model_name='facturevente',
            name='session_caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.sessioncaisse', verbose_name='Session de caisse'),
        ),
        migrations.DeleteModel(
            name='DocumentVente',
        ),
    ]
