# Generated by Django 5.2.6 on 2025-09-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0012_documentvente'),
    ]

    operations = [
    ]
