# Generated by Django 5.2.6 on 2025-09-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0013_auto_20250925_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturetemporaire',
            name='session_key',
            field=models.CharField(max_length=100, verbose_name='Clé de session'),
        ),
    ]
