# Generated by Django 5.2.6 on 2025-09-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0015_factureachat_facturetransfert_inventairestock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturetransfert',
            name='etat',
            field=models.CharField(choices=[('entrer', 'Entrer'), ('sortir', 'Sortir')], default='entrer', max_length=10, verbose_name='État'),
        ),
    ]
