# Generated by Django 5.2.6 on 2025-10-21 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0016_facturetransfert_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturetemporaire',
            name='session_caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarket.sessioncaisse', verbose_name='Session de caisse'),
        ),
        migrations.AlterField(
            model_name='article',
            name='conditionnement',
            field=models.CharField(choices=[('Sac', 'Sac'), ('Sac de 1kg', 'Sac de 1kg'), ('Sac de 5kg', 'Sac de 5kg'), ('Sac de 10kg', 'Sac de 10kg'), ('Sac de 25kg', 'Sac de 25kg'), ('Sac de 50kg', 'Sac de 50kg'), ('Bouteille', 'Bouteille'), ('Bouteille de 0.5L', 'Bouteille de 0.5L'), ('Bouteille de 1L', 'Bouteille de 1L'), ('Bouteille de 1.5L', 'Bouteille de 1.5L'), ('Bouteille de 2L', 'Bouteille de 2L'), ('Bouteille de 5L', 'Bouteille de 5L'), ('Bidon', 'Bidon'), ('Bidon de 5L', 'Bidon de 5L'), ('Bidon de 10L', 'Bidon de 10L'), ('Bidon de 20L', 'Bidon de 20L'), ('Morceau', 'Morceau'), ('Morceau unitaire', 'Morceau unitaire'), ('Morceau de 500g', 'Morceau de 500g'), ('Paquet', 'Paquet'), ('Carton', 'Carton'), ('Boîte', 'Boîte')], max_length=50, verbose_name='Conditionnement'),
        ),
        migrations.AlterField(
            model_name='article',
            name='unite_vente',
            field=models.CharField(choices=[('Sac', 'Sac'), ('Bouteille', 'Bouteille'), ('Morceau', 'Morceau'), ('Bidon', 'Bidon'), ('Kg', 'Kg'), ('Litre', 'Litre'), ('Paquet', 'Paquet'), ('Unité', 'Unité'), ('Carton', 'Carton'), ('Boîte', 'Boîte')], max_length=20, verbose_name='Unité de vente'),
        ),
    ]
