# Generated by Django 5.2.6 on 2025-10-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0017_facturetemporaire_session_caisse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='stock_actuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock actuel'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock_minimum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock minimum'),
        ),
    ]
