# Generated by Django 5.2.6 on 2025-10-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0018_alter_article_stock_actuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignefacturevente',
            name='quantite',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité'),
        ),
    ]
