# Generated by Django 5.2.6 on 2025-10-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0019_alter_lignefacturevente_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité'),
        ),
    ]
