# Generated by Django 5.2.6 on 2025-10-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0021_alter_lignefactureachat_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneinventairestock',
            name='quantite_stock',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité en stock'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite_stock',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité en stock'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='solde',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Solde'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='stock_initial',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Stock initial'),
        ),
    ]
