# Generated by Django 5.2.6 on 2025-11-27 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0022_fix_decimal_quantities_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de la commande')),
                ('heure', models.TimeField(verbose_name='Heure de la commande')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité')),
                ('quantite_totale', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité totale')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix total')),
                ('etat_commande', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='État de la commande')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='supermarket.article', verbose_name='Article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='supermarket.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date', '-heure'],
            },
        ),
        migrations.CreateModel(
            name='FactureCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de la facture')),
                ('heure', models.TimeField(verbose_name='Heure de la facture')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix total')),
                ('net_a_payer', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net à payer')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='supermarket.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Facture de commande',
                'verbose_name_plural': 'Factures de commande',
                'ordering': ['-date', '-heure'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_livraison', models.DateField(verbose_name='Date de livraison')),
                ('heure_livraison', models.TimeField(verbose_name='Heure de livraison')),
                ('etat_livraison', models.CharField(choices=[('en_preparation', 'En préparation'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_preparation', max_length=20, verbose_name='État de la livraison')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='supermarket.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_livraison', '-heure_livraison'],
            },
        ),
        migrations.CreateModel(
            name='StatistiqueClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité')),
                ('nombre_commandes', models.PositiveIntegerField(default=0, verbose_name='Nombre de commandes')),
                ('date_statistique', models.DateField(verbose_name='Date de la statistique')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valeur unitaire')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant total')),
                ('etat_commande', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], max_length=20, verbose_name='État de la commande')),
                ('satisfaction', models.CharField(choices=[('tres_satisfait', 'Très satisfait'), ('satisfait', 'Satisfait'), ('neutre', 'Neutre'), ('insatisfait', 'Insatisfait'), ('non_evalue', 'Non évalué')], default='non_evalue', max_length=20, verbose_name='Satisfaction client')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistiques_client', to='supermarket.article', verbose_name='Article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='supermarket.client', verbose_name='Client')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistiques_client', to='supermarket.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Statistique client',
                'verbose_name_plural': 'Statistiques clients',
                'ordering': ['-date_statistique'],
            },
        ),
    ]
