# Generated by Django 5.2.6 on 2025-11-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0023_commande_facturecommande_livraison_statistiqueclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturecommande',
            name='adresse_commande',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse de livraison'),
        ),
        migrations.AddField(
            model_name='facturecommande',
            name='ville_commande',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville de livraison'),
        ),
    ]
