# Generated by Django 5.2.6 on 2025-11-28 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0024_facturecommande_adresse_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='facturecommande',
            name='commande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='supermarket.commande', verbose_name='Commande'),
        ),
    ]
