# Generated by Django 5.2.6 on 2025-11-28 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0025_client_zone_alter_facturecommande_commande'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livraison',
            options={'ordering': ['date_livraison', 'heure_livraison', 'ordre_livraison'], 'verbose_name': 'Livraison', 'verbose_name_plural': 'Livraisons'},
        ),
        migrations.AddField(
            model_name='livraison',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='ordre_livraison',
            field=models.PositiveIntegerField(default=0, help_text="Ordre dans l'itinéraire", verbose_name='Ordre de livraison'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zone de livraison'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='etat_livraison',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('en_preparation', 'En préparation'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('reportee', 'Reportée'), ('annulee', 'Annulée')], default='planifiee', max_length=20, verbose_name='État de la livraison'),
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.agence', verbose_name='Agence')),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.AddField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='supermarket.livreur', verbose_name='Livreur'),
        ),
    ]
