# Generated by Django 5.2.6 on 2025-11-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0026_alter_livraison_options_livraison_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livraison',
            options={'ordering': ['date_livraison', 'heure_depart', 'ordre_livraison'], 'verbose_name': 'Livraison', 'verbose_name_plural': 'Livraisons'},
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='heure_livraison',
        ),
        migrations.AddField(
            model_name='livraison',
            name='heure_arrivee',
            field=models.TimeField(blank=True, help_text="Heure d'arrivée prévue chez le client", null=True, verbose_name="Heure d'arrivée"),
        ),
        migrations.AddField(
            model_name='livraison',
            name='heure_depart',
            field=models.TimeField(blank=True, help_text='Heure de départ du livreur', null=True, verbose_name='Heure de départ'),
        ),
    ]
