# Generated by Django 5.2.6 on 2025-11-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0027_alter_livraison_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='etat_livraison',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('en_preparation', 'En préparation'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('partiellement_livree', 'Partiellement livrée'), ('pas_livree', 'Pas livrée'), ('reportee', 'Reportée'), ('annulee', 'Annulée')], default='planifiee', max_length=20, verbose_name='État de la livraison'),
        ),
    ]
