# Generated by Django 5.2.6 on 2025-11-28 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0028_alter_livraison_etat_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailLivraisonArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_livree', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantité livrée')),
                ('quantite_non_livree', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantité non livrée')),
                ('raison_non_livraison', models.TextField(blank=True, null=True, verbose_name='Raison de non-livraison')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_livraison', to='supermarket.commande', verbose_name='Commande')),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_articles', to='supermarket.livraison', verbose_name='Livraison')),
            ],
            options={
                'verbose_name': 'Détail livraison article',
                'verbose_name_plural': 'Détails livraison articles',
                'ordering': ['commande__article__designation'],
            },
        ),
    ]
