# Generated by Django 5.2.6 on 2025-11-29 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0029_detaillivraisonarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('commande_enregistree', 'Commande enregistrée'), ('livraison_planifiee', 'Livraison planifiée'), ('livraison_confirmee', 'Livraison confirmée'), ('livraison_terminee', 'Livraison terminée'), ('stock_insuffisant', 'Stock insuffisant'), ('autre', 'Autre')], max_length=50, verbose_name='Type de notification')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.agence', verbose_name='Agence')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='supermarket.commande', verbose_name='Commande')),
                ('livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='supermarket.livraison', verbose_name='Livraison')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['agence', 'lu', '-date_creation'], name='supermarket_agence__f10651_idx')],
            },
        ),
    ]
