# Generated by Django 5.2.6 on 2025-12-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0030_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='type_compte',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('gerant', 'Gérant'), ('caissier', 'Caissier'), ('comptable', 'Comptable'), ('livreur', 'Livreur'), ('acm', 'ACM'), ('responsable_logistique', 'Responsable Logistique'), ('gardien', 'Gardien'), ('magasinier', 'Magasinier'), ('responsable_achat', "Responsable d'Achat"), ('responsable_commercial', 'Responsable Commercial'), ('chef_comptable', 'Chef Comptable')], default='caissier', max_length=30, verbose_name='Type de compte'),
        ),
    ]
