# Generated by Django 5.2.6 on 2025-12-03 10:45

from django.db import migrations, models
from django.utils import timezone
from datetime import date


def set_date_facture_default(apps, schema_editor):
    """Remplir date_facture avec la date de création pour les factures existantes"""
    FactureCommande = apps.get_model('supermarket', 'FactureCommande')
    for facture in FactureCommande.objects.filter(date_facture__isnull=True):
        # Utiliser la date de création si disponible, sinon la date actuelle
        if facture.date_creation:
            facture.date_facture = facture.date_creation.date()
        else:
            facture.date_facture = date.today()
        facture.save()


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0032_add_agence_to_commande_models'),
    ]

    operations = [
        # Étape 1: Ajouter le champ comme nullable temporairement
        migrations.AddField(
            model_name='facturecommande',
            name='date_facture',
            field=models.DateField(null=True, blank=True, verbose_name='Date de facture'),
        ),
        # Étape 2: Remplir les valeurs existantes
        migrations.RunPython(set_date_facture_default, migrations.RunPython.noop),
        # Étape 3: Rendre le champ non-nullable avec valeur par défaut
        migrations.AlterField(
            model_name='facturecommande',
            name='date_facture',
            field=models.DateField(default=date.today, verbose_name='Date de facture'),
        ),
    ]
