# Generated by Django 5.2.6 on 2025-12-04 10:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0035_add_livreur_and_update_livraison'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturecommande',
            options={'ordering': ['-date_facture', '-heure'], 'verbose_name': 'Facture de commande', 'verbose_name_plural': 'Factures de commande'},
        ),
        migrations.AlterModelOptions(
            name='statistiqueclient',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Statistique client', 'verbose_name_plural': 'Statistiques clients'},
        ),
        migrations.RemoveField(
            model_name='facturecommande',
            name='adresse_commande',
        ),
        migrations.RemoveField(
            model_name='facturecommande',
            name='ville_commande',
        ),
        migrations.RemoveField(
            model_name='statistiqueclient',
            name='article',
        ),
        migrations.RemoveField(
            model_name='statistiqueclient',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='statistiqueclient',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='statistiqueclient',
            name='date_statistique',
        ),
        migrations.RemoveField(
            model_name='statistiqueclient',
            name='etat_commande',
        ),
        migrations.RemoveField(
            model_name='statistiqueclient',
            name='nombre_commandes',
        ),
        migrations.RemoveField(
            model_name='statistiqueclient',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='statistiqueclient',
            name='satisfaction',
        ),
        migrations.RemoveField(
            model_name='statistiqueclient',
            name='valeur',
        ),
        migrations.AddField(
            model_name='statistiqueclient',
            name='date_debut',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='statistiqueclient',
            name='date_fin',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='statistiqueclient',
            name='nombre_achats',
            field=models.IntegerField(default=0, verbose_name="Nombre d'achats"),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zone',
            field=models.CharField(default='Non spécifiée', max_length=100, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='etat_commande',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée'), ('validee', 'Validée')], default='en_attente', max_length=20, verbose_name='État de la commande'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='heure',
            field=models.TimeField(verbose_name='Heure'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix total'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='quantite',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='quantite_totale',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantité totale'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='type_compte',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('gerant', 'Gérant'), ('caissier', 'Caissier'), ('vendeur', 'Vendeur'), ('magasinier', 'Magasinier'), ('comptable', 'Comptable')], default='vendeur', max_length=20, verbose_name='Type de compte'),
        ),
        migrations.AlterField(
            model_name='facturecommande',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarket.commande', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='facturecommande',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date de facture'),
        ),
        migrations.AlterField(
            model_name='facturecommande',
            name='heure',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de facture'),
        ),
        migrations.AlterField(
            model_name='facturecommande',
            name='net_a_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Net à payer'),
        ),
        migrations.AlterField(
            model_name='facturecommande',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix total'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarket.commande', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='heure_arrivee',
            field=models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée"),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='heure_depart',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de départ'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.livreur', verbose_name='Livreur'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='ordre_livraison',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre de livraison'),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='statistiqueclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='statistiqueclient',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total'),
        ),
        migrations.CreateModel(
            name='DocumentCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure', models.TimeField(verbose_name='Heure')),
                ('etat_commande', models.CharField(choices=[('en_attente', 'En attente'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée'), ('validee', 'Validée')], default='en_attente', max_length=20, verbose_name='État de la commande')),
                ('quantite_totale', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantité totale')),
                ('prix_total_global', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix total global')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.agence', verbose_name='Agence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Document de commande',
                'verbose_name_plural': 'Documents de commande',
                'ordering': ['-date', '-heure'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire')),
                ('prix_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix total')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.article', verbose_name='Article')),
                ('document_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='supermarket.documentcommande', verbose_name='Document de commande')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'ordering': ['document_commande', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='DetailLivraisonArticle',
        ),
    ]
