# Generated by Django 5.2.6 on 2025-12-04 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0036_alter_facturecommande_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviClientAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_appel', models.TimeField(blank=True, null=True, verbose_name="Heure d'appel")),
                ('action', models.TextField(blank=True, null=True, verbose_name='Action/Commande')),
                ('date_action', models.DateTimeField(auto_now=True, verbose_name="Date de l'action")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.agence', verbose_name='Agence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Action de suivi client',
                'verbose_name_plural': 'Actions de suivi client',
                'ordering': ['-date_action'],
                'unique_together': {('client', 'agence')},
            },
        ),
    ]
