# Generated by Django 5.2.6 on 2025-12-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0037_suiviclientaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Détail'),
        ),
        migrations.AddField(
            model_name='client',
            name='potentiel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Potentiel /5'),
        ),
        migrations.AddField(
            model_name='client',
            name='ref',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence'),
        ),
    ]
