# Generated by Django 5.2.6 on 2025-12-04 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0038_client_detail_client_potentiel_client_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suiviclientaction',
            options={'ordering': ['-date_action', '-heure_appel'], 'verbose_name': 'Action de suivi client', 'verbose_name_plural': 'Actions de suivi client'},
        ),
        migrations.AlterUniqueTogether(
            name='suiviclientaction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='suiviclientaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_suivi', to='supermarket.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='suiviclientaction',
            name='date_action',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action"),
        ),
    ]
