# Generated by Django 5.2.6 on 2025-12-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0039_alter_suiviclientaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='type_compte',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('gerant', 'Gérant'), ('caissier', 'Caissier'), ('vendeur', 'Vendeur'), ('magasinier', 'Magasinier'), ('comptable', 'Comptable'), ('acm', 'ACM'), ('responsable_logistique', 'Responsable Logistique'), ('responsable_rh', 'Responsable Ressource Humaine'), ('assistant_comptable', 'Assistant Comptable'), ('responsable_achat', 'Responsable Achat')], default='vendeur', max_length=30, verbose_name='Type de compte'),
        ),
    ]
