# Generated by Django 5.2.6 on 2025-01-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0042_add_livreur_type_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='suiviclientaction',
            name='plage_horaire',
            field=models.CharField(blank=True, choices=[('06h30-08h30', '06h30-08h30'), ('08h30-10h00', '08h30-10h00'), ('10h00-11h30', '10h00-11h30'), ('14h30-16h00', '14h30-16h00'), ('16h00-17h30', '16h00-17h30')], max_length=20, null=True, verbose_name='Plage horaire'),
        ),
    ]




