# Generated by Django 6.0.1 on 2026-01-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0045_depense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiffreAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('montant_previsionnel', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Objectif (CAP)')),
                ('montant_realise', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Réalisé (CAR)')),
            ],
            options={
                'verbose_name': "Chiffre d'Affaire",
                'verbose_name_plural': "Chiffres d'Affaires",
                'ordering': ['-date'],
            },
        ),
    ]
