# Generated by Django 6.0.1 on 2026-01-13 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0046_chiffreaffaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiffreaffaire',
            name='agence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supermarket.agence', verbose_name='Agence'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='chiffreaffaire',
            unique_together={('agence', 'date')},
        ),
    ]
