# Generated by Django 6.0.1 on 2026-01-13 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0047_chiffreaffaire_agence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='agence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supermarket.agence', verbose_name='Agence'),
            preserve_default=False,
        ),
    ]
