# Generated by Django 6.0.1 on 2026-01-14 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0048_depense_agence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tresorerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('banque_initial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde Banque Initial')),
                ('banque_depot', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dépôt Banque')),
                ('banque_retrait', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retrait Banque')),
                ('solde_caisse', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde Caisse Physique')),
                ('om_initial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde OM Initial')),
                ('om_depot', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dépôt OM')),
                ('om_retrait', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retrait OM')),
                ('momo_initial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde MOMO Initial')),
                ('momo_depot', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dépôt MOMO')),
                ('momo_retrait', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retrait MOMO')),
                ('montant_sav', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant SAV')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.agence', verbose_name='Agence')),
            ],
            options={
                'verbose_name': 'Trésorerie',
                'verbose_name_plural': 'Trésoreries',
                'ordering': ['-date'],
                'unique_together': {('agence', 'date')},
            },
        ),
    ]
