# Generated by Django 6.0.1 on 2026-01-14 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0049_tresorerie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tresorerie',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='tresorerie',
            name='montant_sav',
        ),
        migrations.RemoveField(
            model_name='tresorerie',
            name='solde_caisse',
        ),
        migrations.AddField(
            model_name='tresorerie',
            name='caisse_entree',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tresorerie',
            name='caisse_initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tresorerie',
            name='caisse_sortie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tresorerie',
            name='sav_entree',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tresorerie',
            name='sav_initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tresorerie',
            name='sav_sortie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tresorerie',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.agence'),
        ),
        migrations.AlterField(
            model_name='tresorerie',
            name='banque_depot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tresorerie',
            name='banque_initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tresorerie',
            name='banque_retrait',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tresorerie',
            name='momo_depot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tresorerie',
            name='momo_initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tresorerie',
            name='momo_retrait',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tresorerie',
            name='om_depot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tresorerie',
            name='om_initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tresorerie',
            name='om_retrait',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
