# Generated by Django 6.0.1 on 2026-01-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0049_add_analyste_financiere_type_compte'),
        ('supermarket', '0050_alter_tresorerie_options_and_more'),
    ]

    operations = [
    ]
