# Generated by Django 6.0.1 on 2026-01-19 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0051_merge_20260119_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe_depanse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.agence')),
            ],
            options={
                'verbose_name': 'Employé',
                'unique_together': {('agence', 'nom_complet')},
            },
        ),
        migrations.AddField(
            model_name='depense',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.employe_depanse', verbose_name='Bénéficiaire'),
        ),
    ]
