# Generated by Django 6.0.1 on 2026-01-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0052_employe_depanse_depense_employe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employe_depanse',
            new_name='Beneficiaire',
        ),
        migrations.AlterModelOptions(
            name='beneficiaire',
            options={'verbose_name': 'Bénéficiaire Dépense'},
        ),
        migrations.RenameField(
            model_name='depense',
            old_name='employe',
            new_name='beneficiaire',
        ),
    ]
