# Generated by Django 6.0.1 on 2026-01-22 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0053_rename_employe_depanse_beneficiaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MargePersonnalisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mauvaise_min', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Mauvaise : De (%)')),
                ('mauvaise_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Mauvaise : À (%)')),
                ('bonne_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Bonne : De (%)')),
                ('bonne_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Bonne : À (%)')),
                ('tres_bonne_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Très Bonne : De (%)')),
                ('tres_bonne_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Très Bonne : À (%)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.agence', verbose_name='Agence')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='supermarket.article', verbose_name='Article concerné')),
            ],
            options={
                'verbose_name': 'Configuration Marge Article',
                'verbose_name_plural': 'Configurations Marges Articles',
                'ordering': ['ordre', 'article__designation'],
                'unique_together': {('agence', 'article')},
            },
        ),
    ]
