# Generated by Django 5.2.6 on 2026-01-19 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0053_rename_employe_depanse_beneficiaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MargePersonnalisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('marge_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Marge minimale (%)')),
                ('marge_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Marge maximale (%)')),
                ('couleur', models.CharField(default='#28a745', max_length=20, verbose_name="Couleur d'affichage")),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.agence', verbose_name='Agence')),
            ],
            options={
                'verbose_name': 'Marge Personnalisée',
                'verbose_name_plural': 'Marges Personnalisées',
                'ordering': ['agence', 'ordre', 'marge_min'],
                'unique_together': {('agence', 'nom_categorie')},
            },
        ),
        migrations.CreateModel(
            name='AssignationMargeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.agence', verbose_name='Agence')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.article', verbose_name='Article')),
                ('marge_personnalisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.margepersonnalisee', verbose_name='Catégorie de marge')),
            ],
            options={
                'verbose_name': 'Assignation Marge Article',
                'verbose_name_plural': 'Assignations Marge Article',
                'ordering': ['-date_modification'],
                'unique_together': {('agence', 'article')},
            },
        ),
    ]
