# Generated by Django 5.2.6 on 2026-01-23 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0054_margepersonnalisee'),
    ]

    operations = [
        migrations.AddField(
            model_name='margepersonnalisee',
            name='article',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='supermarket.article', verbose_name='Article concerné'),
        ),
    ]
