# Generated by Django 5.2.6 on 2026-01-23 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0055_add_article_to_margepersonnalisee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('date_commande', models.DateField(verbose_name='Date de commande')),
                ('date_livraison_prevue', models.DateField(verbose_name='Date de livraison prévue')),
                ('adresse_livraison', models.TextField(verbose_name='Adresse de livraison')),
                ('nom_fournisseur', models.CharField(max_length=200, verbose_name='Nom du fournisseur')),
                ('adresse_fournisseur', models.TextField(verbose_name='Adresse du fournisseur')),
                ('telephone_fournisseur', models.CharField(blank=True, max_length=20, verbose_name='Téléphone fournisseur')),
                ('email_fournisseur', models.EmailField(blank=True, max_length=254, verbose_name='Email fournisseur')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total HT')),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TVA')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TTC')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.agence', verbose_name='Agence')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Commande Fournisseur',
                'verbose_name_plural': 'Commandes Fournisseur',
                'ordering': ['-date_commande', '-numero_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.article', verbose_name='Article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='supermarket.commandefournisseur', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Ligne Commande Fournisseur',
                'verbose_name_plural': 'Lignes Commande Fournisseur',
                'ordering': ['commande', 'id'],
            },
        ),
    ]
