# Generated by Django 5.2.6 on 2026-01-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0056_commande_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='numero_entreprise',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'entreprise"),
        ),
        migrations.AddField(
            model_name='agence',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo de l\'entreprise'),
        ),
        migrations.AddField(
            model_name='agence',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='agence',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='agence',
            name='site_web',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
    ]
