# Generated by Django 6.0.1 on 2026-01-27 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0059_add_taux_tva_to_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='margepersonnalisee',
            name='article',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='supermarket.article', verbose_name='Article concerné'),
            preserve_default=False,
        ),
    ]
