# Generated by Django 6.0.1 on 2026-01-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0060_alter_margepersonnalisee_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommandefournisseur',
            name='delai_paiement',
            field=models.DateField(blank=True, null=True, verbose_name='Échéance de paiement'),
        ),
    ]
