# Generated by Django 6.0.1 on 2026-01-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0061_lignecommandefournisseur_delai_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandefournisseur',
            name='delai_paiement',
            field=models.DateField(blank=True, null=True, verbose_name='Échéance de paiement'),
        ),
    ]
