# Generated by Django 5.2.6 on 2026-02-03 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0062_commandefournisseur_delai_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviCommercialAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_visite', models.TimeField(blank=True, null=True, verbose_name='Heure de visite')),
                ('action', models.TextField(blank=True, null=True, verbose_name='Action/Commande')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.agence', verbose_name='Agence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_suivi_commercial', to='supermarket.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_suivi_commercial_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Action de suivi commercial',
                'verbose_name_plural': 'Actions de suivi commercial',
                'ordering': ['-date_action', '-heure_visite'],
            },
        ),
    ]
