# Generated by Django 5.2.6 on 2026-02-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0064_alter_compte_type_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivicommercialaction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='suivi_commercial/photos/', verbose_name='Photo'),
        ),
    ]
